export const experience = [
  { company: 'Citi Bank', role: 'Associate Vice President', location: 'Pune', dates: 'Jul 2025 — Present', summary: 'Modernizing the data foundations behind risk and reporting.', details: ['Maintain Python backends and BAU dashboards for Risk and Reporting operations.', 'Led Talend-to-Python ETL migration with 100% accuracy and successful completion.', 'Led Apache Ignite-to-Oracle (ORaaS) migration as part of three migration initiatives.', 'Built an end-to-end Python application with API support to migrate Oracle data to ORaaS.'], stack: ['Python', 'Oracle', 'Talend', 'Apache Ignite'] },
  { company: 'Snowflake', role: 'Senior Cloud Engineer', location: 'Pune', dates: 'Feb 2025 — Jul 2025', summary: 'Connecting business systems to reliable analytics datasets.', details: ['Designed and maintained Snowflake pipelines integrating Salesforce and other business systems for multiple clients.', 'Built SQL and dbt transformations for reporting and analytics.', 'Managed integration, monitored performance, and resolved load failures.', 'Earned Snowflake Core Certification.'], stack: ['Snowflake', 'SQL', 'dbt', 'Salesforce'] },
  { company: 'KetteQ', role: 'Senior Technical Consultant', location: 'Pune', dates: 'Oct 2022 — Feb 2025', summary: 'Delivering client migrations and automated cloud integrations.', details: ['Developed Talend data migration solutions for multiple clients.', 'Automated recurring API calls and scheduled data loads using Mage.', 'Built custom Salesforce pipelines and managed end-to-end integration.'], stack: ['AWS', 'Python', 'Mage', 'ClickHouse', 'Talend', 'dbt'] },
  { company: 'TIAA GBS', role: 'Consultant', location: 'Mumbai', dates: 'Jun 2021 — Oct 2022', summary: 'Keeping production data moving, with 60% faster request resolution.', details: ['Supported production ETL jobs using PySpark, DataStage, Oracle, and UNIX.', 'Monitored daily flows and managed execution against client SLAs.', 'Built request-handling automation that reduced mean time to resolution by 60%.', 'Coordinated recovery from processing delays and resolved data incidents.'], stack: ['PySpark', 'DataStage', 'AWS', 'Snowflake', 'Python'] },
  { company: 'Deloitte USI', role: 'Consultant', location: 'Mumbai', dates: 'Jul 2019 — Jun 2021', summary: 'Engineering and validating data for healthcare and insurance.', details: ['Developed end-to-end PySpark and Airflow ETL jobs for a US healthcare provider.', 'Automated daily operations with Python and built a Django ticket management and deployment application.', 'Validated reporting consistency across Cognos and Tableau.', 'Tested AWS ETL and Accounting Sub Ledger applications for a European insurer; automated time-consuming test queries.'], stack: ['PySpark', 'Airflow', 'AWS Glue', 'Django', 'Python'] },
  { company: 'LTI', role: 'Sr. Software Developer', location: 'Mumbai', dates: 'Feb 2018 — Jul 2019', summary: 'From real-time ingestion to cross-platform ETL migration.', details: ['Built real-time JSON and XML log ingestion using Kafka and PySpark for a Nordic financial services provider.', 'Maintained DataStage data quality workflows.', 'Migrated Cognos Data Manager builds to DataStage for a French water management company.', 'Coordinated iterative deliveries with a 20-member team and created Oracle activity hierarchies.'], stack: ['Kafka', 'PySpark', 'DataStage', 'Oracle'] },
  { company: 'Capgemini', role: 'Consultant', location: 'Mumbai', dates: 'Oct 2016 — Jan 2018', summary: 'Turning recurring reporting work into automated insight.', details: ['Supported DataStage jobs for Sales Performance Management and met all assigned targets.', 'Worked with Teradata as the primary client database.', 'Automated KPI dashboards using Excel and VBA, saving 5 FTE.'], stack: ['DataStage', 'Teradata', 'Excel', 'VBA'] },
  { company: 'IBM', role: 'Data Specialist', location: 'Kolkata', dates: 'Sep 2013 — Sep 2016', summary: 'Building a foundation in enterprise data and delivery leadership.', details: ['Developed DataStage jobs extracting from multiple SAP sources and loading an SAP target.', 'Automated Excel data profiling with VBA, saving 2 FTE.', 'Led an 8-member team delivering migrations with Cransoft DSP and met all migration SLAs.'], stack: ['DataStage', 'SAP', 'Cransoft DSP', 'VBA'] },
];
export const skills = [
  { title: 'Data engineering', number: '01', items: ['Python', 'SQL', 'PySpark', 'DataStage', 'Talend', 'UNIX'] },
  { title: 'Cloud & platforms', number: '02', items: ['AWS S3', 'Redshift', 'Glue', 'Lambda', 'EC2', 'CloudWatch', 'Snowflake'] },
  { title: 'Pipelines & databases', number: '03', items: ['Airflow', 'dbt', 'Mage', 'Kafka', 'Oracle', 'SQL Server', 'Teradata', 'ClickHouse', 'Jenkins'] },
  { title: 'Analytics & beyond', number: '04', items: ['Tableau', 'Cognos', 'Excel / VBA', 'Hadoop', 'Hive', 'Sqoop', 'Flume', 'Regression', 'SVM', 'Random Forest', 'Decision Tree', 'Naïve Bayes', 'KNN', 'K-Means'] },
];
export const awards = [
  ['IBM', 'Orion Award', 'Recognized for putting the client first.'],
  ['IBM', 'Deep Skill · Manager’s Choice · Innovation Recognition', 'Three additional awards for technical skill and contribution.'],
  ['Capgemini', 'Project Star Award', 'Recognition for project contributions.'],
  ['LTI', 'Certificate of Appreciation', 'Helping conduct interviews for the Analytics business unit.'],
  ['Deloitte USI', 'Certificate of Recognition', 'Unit testing automation that reduced manual effort.'],
  ['TIAA', 'Automation appreciation', 'Request automation that reduced MTTR by 60%.'],
];
